# Generated by Django 3.2.9 on 2021-11-27 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20211127_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='password_1',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=64, verbose_name='Hasło'),
        ),
    ]
